Update venue part2
samantabhadra77/ichiyasaGitSample pull request #2
Opened 2024-10-13 18:01 UTC by samantabhadra77

失敗したのでやり直し。

2024-10-14 08:24 UTC, hsyfam commented
一言コメント。

2024-10-14 08:27 UTC, samantabhadra77 commented
### ヘディング
**太字**
_斜体_

> あ

1. あ
2. い
3. う

2024-10-17 16:30 UTC, hsyfam commented on README.md
> -『いちばんやさしいGit&GitHubの教本』のサンプルプロジェクト
ほうほう、なるほど。

2024-10-17 16:32 UTC, hsyfam commented on README.md
> -『いちばんやさしいGit&GitHubの教本』のサンプルプロジェクト
やはり指摘止めよっかな…。

2024-10-17 16:33 UTC, samantabhadra77 commented on README.md
> -『いちばんやさしいGit&GitHubの教本』のサンプルプロジェクト
嫌々そんなこと言わないで…。

2024-10-17 16:54 UTC, hsyfam reviewed
あああああ

2024-10-17 16:54 UTC, hsyfam commented on README.md
> +『いちばんやさしいGit&GitHubの教本』のサンプルプロジェクトです。
RVを開始します。

2024-10-17 16:54 UTC, hsyfam commented on index.html
>                          <h3>スピーカー</h3>
こっちはどうだ？

2024-10-17 16:58 UTC, hsyfam commented on README.md
> -『いちばんやさしいGit&GitHubの教本』のサンプルプロジェクト
RVとRVの間？

2024-10-17 17:02 UTC, hsyfam commented on README.md
> +『いちばんやさしいGit&GitHubの教本』のサンプルプロジェクトです。
RVとRVの間？２

2024-10-17 17:03 UTC, hsyfam requested changes
ｆｆｆｆｆ

2024-10-17 17:14 UTC, hsyfam commented
ここでのコメントは？

2024-10-17 17:18 UTC, hsyfam requested changes
４点指摘したので変更してください。

2024-10-17 17:18 UTC, hsyfam commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
インプレスをインプレッサに変えてください。

2024-10-17 17:18 UTC, hsyfam commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
イベントをイベンツに変えてください。

2024-10-17 17:18 UTC, hsyfam commented on README.md
> +『いちばんやさしいGit&GitHubの教本』のサンプルプロジェクトです。
サンプルプロジェクトです？にしてください。

2024-10-17 17:18 UTC, hsyfam commented on README.md
> +『いちばんやさしいGit&GitHubの教本』のサンプルプロジェクトです。
やはりです？？にしてください。

2024-10-17 18:01 UTC, samantabhadra77 commented
RV1回目の指摘を対応しました。

2024-10-17 18:02 UTC, hsyfam commented
ご対応ありがとうございました。修正問題ありません。

2024-10-17 18:04 UTC, hsyfam approved these changes

2024-10-18 21:06 UTC, merged